version: "3.9"
networks:
   enduro-portal-dev:
      driver: bridge

services:
   user_web_api:
      container_name: user_web_api
      build:
         context: .
         dockerfile: ./src/UserWebApi/Dockerfile
      ports:
        - 8080:8080
      environment:
        - ASPNETCORE_HTTP_PORTS=8080  
      networks:
        - enduro-portal-dev
      depends_on:
        - grpc_server

   admin_web_api:
      container_name: admin_web_api
      build:
         context: .
         dockerfile: ./src/AdminWebApi/Dockerfile
      ports:
        - 8082:8082
      environment:
        - ASPNETCORE_HTTP_PORTS=8082
      networks:
        - enduro-portal-dev
      depends_on:
        - grpc_server

   grpc_server:
        container_name: grpc_server
        build:
          context: .
          dockerfile: ./src/EnduroPortal.GrpcServer/Dockerfile
        depends_on:
          - app_db
        networks:
          - enduro-portal-dev
        ports:
          - 7265:7265
        environment:
          - ASPNETCORE_HTTP_PORTS=7265
          - ConnectionStrings__DefaultConnection=User ID =admin;Password=password;Server=app_db;Port=5432;Database=EnduroPortal; Integrated Security=true;Pooling=true;

   app_db:
     image: postgres:latest
     container_name: app_db
     environment:
       - POSTGRES_DB=EnduroPortal
       - POSTGRES_USER=admin
       - POSTGRES_PASSWORD=password
     ports:
       - "5433:5432"
     restart: always
     volumes:
       - app_data:/var/lib/postgresql/data
     networks:
       - enduro-portal-dev

volumes:
  app_data: