version: "3.9"
networks:
   enduro-portal-dev:
      driver: bridge

services:
   user_web_api:
      container_name: user_web_api
      build:
         context: .
         dockerfile: ./src/UserWebApi/Dockerfile
      ports:
        - 8080:8080
      environment:
        - ASPNETCORE_HTTP_PORTS=8080  
      networks:
        - enduro-portal-dev
      depends_on:
        - grpc_server

   grpc_server:
        container_name: grpc_server
        build:
          context: .
          dockerfile: ./src/EnduroPortal.GrpcServer/Dockerfile
        networks:
        - enduro-portal-dev
        ports:
          - 7265:7265
        environment:
          - ASPNETCORE_HTTP_PORTS=7265